---
- name: Install AD DFS
  hosts: server
  gather_facts: false
  tasks:
    - name: Install AD DFS
      ansible.windows.win_feature:
        name:
          - FS-DFS-Namespace
          - FS-DFS-Replication
        state: present
        include_management_tools: true

    - name: Create directories
      ansible.windows.win_file:
        path: "{{ item.path }}"
        state: "{{ item.state }}"
      loop: "{{ addfs }}"
    
    - name: Create SMB shares
      ansible.windows.win_share:
        name: "{{ item.name }}"
        path: "{{ item.path }}"
        full: "{{ item.full }}"
        change: "{{ item.change }}"
        read: "{{ item.read }}"
      loop: "{{ addfs }}"

- name: Configure AD DFS
  hosts: kkk-adds
  gather_facts: false
  tasks:
    - name: Check namespace root
      ansible.windows.win_shell: '(Get-DfsnRoot | Where-Object { $_.Path -like "\\KKK.COM\Files" }) -ne $null'
      register: dfsn
      changed_when: '"True" not in dfsn.stdout'
      notify: Configure DFS

  handlers:
    - name: Create namespace root
      ansible.windows.win_shell: 'New-DfsnRoot -Path "\\KKK.COM\Files" -TargetPath "\\KKK-ADDS.kkk.com\Files" -Type DomainV2'
      listen: Configure DFS

    - name: Create namespace folders
      ansible.windows.win_shell: |
        New-DfsnFolder -Path '\\KKK.COM\Files\"{{ item.name }}"' -TargetPath '\\KKK-ADDS.kkk.com\"{{ item.name }}"'
      loop: "{{ addfs }}"
      listen: Configure DFS

    - name: Add folder secondary paths
      ansible.windows.win_shell: |
        New-DfsnFolder -Path '\\KKK.COM\Files\"{{ item.name }}"' -TargetPath '\\KKK-ADDS.kkk.com\"{{ item.name }}"' -State Online
      loop: "{{ addfs }}"
      listen: Configure DFS

    - name: Create replication group
      ansible.windows.win_shell: New-DfsReplicationGroup -GroupName "KKK-REPLICATION"
      listen: Configure DFS

    - name: Add servers to replication group
      ansible.windows.win_shell: Add-DfsrMember -GroupName "KKK-REPLICATION" -ComputerName "KKK-ADDS.kkk.com", "KKK-RODC.kkk.com"
      listen: Configure DFS

    - name: Set replicated folder
      ansible.windows.win_shell: |
        New-DfsReplicatedFolder -GroupName "KKK-REPLICATION" -FolderName Files,it,marketing,kiado,adminisztracio,vezeto,zene,KKK
      listen: Configure DFS

    - name: Create replication connection
      ansible.windows.win_shell: >
        Add-DfsrConnection
        -GroupName "KKK-REPLICATION"
        -SourceComputerName "KKK-ADDS.kkk.com"
        -DestinationComputerName "KKK-RODC.kkk.com"
      listen: Configure DFS

    - name: Set local path
      ansible.windows.win_shell: >
        Set-DfsrMembership
        -Groupname "KKK-REPLICATION"
        -FolderName "{{ item.name }}"
        -ComputerName "KKK-ADDS.kkk.com"
        -ContentPath "{{ item.path }}"
        -PrimaryMember $True
        -StagingPathQuotaInMB 16384
        -Force

        Set-DfsrMembership
        -Groupname "KKK-REPLICATION"
        -FolderName "{{ item.name }}"
        -ComputerName "KKK-RODC.kkk.com"
        -ContentPath "{{ item.path }}"
        -Force
      loop: "{{ addfs }}"
      listen: Configure DFS
