---
- name: Install AD DFS
  hosts: server
  gather_facts: true
  tasks:
    - name: Install AD DFS
      ansible.windows.win_feature:
        name:
          - FS-DFS-Namespace
          - FS-DFS-Replication
        state: present
        include_management_tools: true

    - name: Create top directory
      ansible.windows.win_file:
        path: C:\Files
        state: directory

    - name: Create SMB dir
      ansible.windows.win_share:
        name: Files
        path: C:\Files
        full: IT,Domain Admins
        change: IT,Domain Admins
        read: Everyone

    - name: Create Marketing directory
      ansible.windows.win_file:
        path: C:\Marketing
        state: directory

    - name: Create HR directory
      ansible.windows.win_file:
        path: C:\HR
        state: directory

    - name: Create IT directory
      ansible.windows.win_file:
        path: C:\IT
        state: directory

    - name: Create SMB shares (1/3)
      ansible.windows.win_share:
        name: Marketing
        path: C:\Marketing
        full: Admins,Marketing,Domain Admins
        change: Admins

    - name: Create SMB shares (2/3)
      ansible.windows.win_share:
        name: HR
        path: C:\HR
        full: Admins,HR,Domain Admins
        change: Admins

    - name: Create SMB shares (3/3)
      ansible.windows.win_share:
        name: IT
        path: C:\IT
        full: Admins,IT,Domain Admins
        change: Admins

- name: Configure AD DFS
  hosts: server
  gather_facts: true
  become: true
  become_method: runas
  tasks:
    - name: Check namespace root
      ansible.windows.win_shell: '(Get-DfsnRoot | Where-Object { $_.Path -like "\\KKK.COM\Files" }) -ne $null'
      register: dfsn
      changed_when: '"True" not in dfsn.stdout'
      notify: Configure DFS

  handlers:
    - name: Create namespace root
      ansible.windows.win_shell: 'New-DfsnRoot -Path "\\KKK.COM\Files" -TargetPath "\\KKK-ADDS.kkk.com\Files" -Type DomainV2'
      listen: Configure DFS

    - name: Create namespace folders
      ansible.windows.win_shell: |
        New-DfsnFolder -Path '\\KKK.COM\Files\Marketing' -TargetPath '\\KKK-ADDS.kkk.com\Marketing'
        New-DfsnFolder -Path '\\KKK.COM\Files\HR' -TargetPath '\\KKK-ADDS.kkk.com\HR'
        New-DfsnFolder -Path '\\KKK.COM\Files\IT' -TargetPath '\\KKK-ADDS.kkk.com\IT'
      listen: Configure DFS

    - name: Add folder secondary paths
      ansible.windows.win_shell: |
        New-DfsnFolderTarget -Path '\\KKK.COM\Files\Marketing' -TargetPath '\\KKK-RODC.kkk.com\Marketing' -State Online
        New-DfsnFolderTarget -Path '\\KKK.COM\Files\HR' -TargetPath '\\KKK-RODC.kkk.com\HR' -State Online
        New-DfsnFolderTarget -Path '\\KKK.COM\Files\IT' -TargetPath '\\KKK-RODC.kkk.com\IT' -State Online
      listen: Configure DFS

    - name: Create replication group
      ansible.windows.win_shell: New-DfsReplicationGroup -GroupName "KKK-REPLICATION"
      listen: Configure DFS

    - name: Add servers to replication group
      ansible.windows.win_shell: Add-DfsrMember -GroupName "KKK-REPLICATION" -ComputerName "KKK-ADDS.kkk.com", "KKK-RODC.kkk.com"
      listen: Configure DFS

    - name: Set replicated folder
      ansible.windows.win_shell: |
        New-DfsReplicatedFolder -GroupName "KKK-REPLICATION" -FolderName Files,IT,Marketing,HR
      listen: Configure DFS

    - name: Create replication connection
      ansible.windows.win_shell: >
        Add-DfsrConnection
        -GroupName "KKK-REPLICATION"
        -SourceComputerName "KKK-ADDS.kkk.com"
        -DestinationComputerName "KKK-RODC.kkk.com"
      listen: Configure DFS

    - name: Set local path
      ansible.windows.win_shell: >
        Set-DfsrMembership
        -Groupname "KKK-REPLICATION"
        -FolderName "{{ item }}"
        -ComputerName "KKK-ADDS.kkk.com"
        -ContentPath "C:\{{ item }}"
        -PrimaryMember $True
        -StagingPathQuotaInMB 16384
        -Force

        Set-DfsrMembership
        -Groupname "KKK-REPLICATION"
        -FolderName "{{ item }}"
        -ComputerName "KKK-RODC.kkk.com"
        -ContentPath "C:\{{ item }}"
        -Force
      loop: "{{ replication.folders }}"
      listen: Configure DFS
