---
    - name: DHCP configuration
      hosts: KKK-ADDS
      gather_facts: false
      tasks:
      - name: Install DHCP
          ansible.windows.win_feature:
            name:
              - DHCP
            state: present
            include_management_tools: true
          notify: Configure DHCP
    
      handlers:
        - name: Create scopes
          ansible.windows.win_shell: >
            
          listen: Configure DHCP
    
        - name: Edit DHCP scopes
          ansible.windows.win_shell: >
            
          listen: Configure DHCP
      