all:
  vars:
    ansible_user: Administrator@KKK.COM
    ansible_password: Password123
    ansible_connection: winrm
    ansible_port: 5985
    ansible_winrm_transport: basic
    ansible_winrm_server_cert_validation: ignore
    ansible_become_method: runas
    ansible_become_user: KKK\Administrator
    ansible_become_password: Password123
    
    addfs:
      - name: Files
        path: C:\Files
        state: directory
        full: IT
        change: IT
        read: Everyone

      - name: Adminisztracio
        path: C:\Adminisztracio
        state: directory
        full: IT
        change: Adminisztracio
        read: Vezeto
      
      - name: It
        path: C:\It
        state: directory
        full: IT
        change: IT
        read: Vezeto
      
      - name: Kiado
        path: C:\Kiado
        state: directory
        full: IT
        change: Kiado
        read: Vezeto
      
      - name: Marketing
        path: C:\Marketing
        state: directory
        full: IT
        change: Marketing
        read: Vezeto
      
      - name: Vezeto
        path: C:\Vezeto
        state: directory
        full: IT
        change: Vezeto
        read: Vezeto
      
      - name: Zene
        path: C:\Zene
        state: directory
        full: IT
        change: Zene
        read: Vezeto
      
      - name: KKK
        path: C:\KKK
        state: directory
        full: IT
        change: IT
        read: Everyone

    dhcp:
      scopev4:
        - name: "ADMINISZTRACIO"
          start: "10.11.47.2" 
          end: "10.11.47.28"
          netmask: "255.255.255.224"
          scopeid: "10.11.47.0"
          dns: "10.11.113.10"
          wins: "10.11.113.10"
          gateway: "10.11.47.1"
        
        - name: "MARKETING"
          start: "10.11.73.2" 
          end: "10.11.73.60"
          netmask: "255.255.255.192"
          scopeid: "10.11.73.0"
          dns: "10.11.113.10"
          wins: "10.11.113.10"
          gateway: "10.11.73.1"
        
        - name: "VEZETO"
          start: "10.11.71.2" 
          end: "10.11.71.12"
          netmask: "255.255.255.240"
          scopeid: "10.11.71.0"
          dns: "10.11.113.10"
          wins: "10.11.113.10"
          gateway: "10.11.71.1"
        
        - name: "KIADO"
          start: "10.11.97.2" 
          end: "10.11.97.28"
          netmask: "255.255.255.224"
          scopeid: "10.11.97.0"
          dns: "10.11.113.10"
          wins: "10.11.113.10"
          gateway: "10.11.97.1"
        
        - name: "ZENE"
          start: "10.11.19.2" 
          end: "10.11.19.60"
          netmask: "255.255.255.192"
          scopeid: "10.11.19.0"
          dns: "10.11.113.10"
          wins: "10.11.113.10"
          gateway: "10.11.19.1"
        
        - name: "WIFI"
          start: "10.11.140.2" 
          end: "10.11.143.250"
          netmask: "255.255.252.0"
          scopeid: "10.11.140.0"
          dns: "10.11.113.10"
          wins: "10.11.113.10"
          gateway: "10.11.140.1"
        
        - name: "IT"
          start: "10.11.169.2" 
          end: "10.11.169.12"
          netmask: "255.255.255.240"
          scopeid: "10.11.169.0"
          dns: "10.11.113.10"
          wins: "10.11.113.10"
          gateway: "10.11.169.1"
      
      scopev6:
        - name: "ADMINISZTRACIO"
          exstart: "2001:db8:c1c1:abb1:1::" 
          exend: "2001:db8:c1c1:abb1:ffff:ffff:ffff:ffff"
          prefix: "2001:db8:c1c1:abb1::"
        
        - name: "MARKETING"
          exstart: "2001:db8:c1c1:abf8:1::" 
          exend: "2001:db8:c1c1:abf8:ffff:ffff:ffff:ffff"
          prefix: "2001:db8:c1c1:abf8::"
        
        - name: "VEZETO"
          exstart: "2001:db8:c1c1:abba:1::" 
          exend: "2001:db8:c1c1:abba:ffff:ffff:ffff:ffff"
          prefix: "2001:db8:c1c1:abba::"
        
        - name: "KIADO"
          exstart: "2001:db8:c1c1:abf6:1::" 
          exend: "2001:db8:c1c1:abf6:ffff:ffff:ffff:ffff"
          prefix: "2001:db8:c1c1:abf6::"
        
        - name: "ZENE"
          exstart: "2001:db8:c1c1:ab8d:1::" 
          exend: "2001:db8:c1c1:ab8d:ffff:ffff:ffff:ffff"
          prefix: "2001:db8:c1c1:ab8d::"
        
        - name: "WIFI"
          exstart: "2001:db8:c1c1:abda:1::" 
          exend: "2001:db8:c1c1:abda:ffff:ffff:ffff:ffff"
          prefix: "2001:db8:c1c1:abda::"
        
        - name: "IT"
          exstart: "2001:db8:c1c1:abb5:1::" 
          exend: "2001:db8:c1c1:abb5:ffff:ffff:ffff:ffff"
          prefix: "2001:db8:c1c1:abb5::"
    
    dns:
      reversezones:
        - networkid: "10.11.113.0/24"
          name: "113.11.10.in-addr.arpa"

        - networkid: "10.11.199.0/24"
          name: "199.11.10.in-addr.arpa"

        - networkid: "2001:db8:c1c1:abfa::/64"
          name: "a.f.b.a.1.c.1.c.8.b.d.0.1.0.0.2.ip6.arpa"

        - networkid: "2001:db8:c1c1:abb5::/64"
          name: "5.b.b.a.1.c.1.c.8.b.d.0.1.0.0.2.ip6.arpa"


      a_records:
        - name: "kkk-lin"
          value: "10.11.113.5"
          zonename: "kkk.com"

        - name: "kkk-vpn"
          value: "10.11.199.5"
          zonename: "kkk.com"

        - name: "kkk-backup"
          value: "10.11.113.12"
          zonename: "kkk.com"
      
      reverse_a_records:
        - name: "kkk-adds"
          value: "10.11.113.5"
          zonename: "kkk.com"

        - name: "kkk-vpn"
          value: "10.11.199.5"
          zonename: "kkk.com"

        - name: "kkk-backup"
          value: "10.11.113.12"
          zonename: "kkk.com"
      
      reverse_aaaa_records:
        - name: "kkk-lin"
          value: "10.11.113.5"
          zonename: "kkk.com"

        - name: "kkk-vpn"
          value: "10.11.199.5"
          zonename: "kkk.com"

        - name: "kkk-backup"
          value: "10.11.113.12"
          zonename: "kkk.com"

      aaaa_records:
        - name: "kkk-lin"
          value: "2001:db8:c1c1:abfa::5"
          zonename: "kkk.com"

        - name: "kkk-backup"
          value: "2001:db8:c1c1:abfa::12"
          zonename: "kkk.com"

        - name: "kkk-vpn"
          value: "2001:db8:c1c1:abb5::5"
          zonename: "kkk.com"

      cname_records:
        - name: "mail"
          value: "kkk-lin.kkk.com"
          zonename: "kkk.com"
        
        - name: "log"
          value: "kkk-lin.kkk.com"
          zonename: "kkk.com"

        - name: "python"
          value: "kkk-lin.kkk.com"
          zonename: "kkk.com"
          
        - name: "radius"
          value: "kkk-adds.kkk.com"
          zonename: "kkk.com"

        - name: "file"
          value: "kkk-adds.kkk.com"
          zonename: "kkk.com"
        
        - name: "vpn"
          value: "kkk-vpn.kkk.com"
          zonename: "kkk.com"

mainhq:
  children:
    server:
      hosts:
        KKK-ADDS:
          ansible_host: 10.11.113.10
          hostname: KKK-ADDS

        KKK-RODC:
          ansible_host: 10.11.113.11
          hostname: KKK-RODC
